# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbuild, mbot2, random
import time

@event.start
def on_start():
    cyberpi.console.set_font(12)
    cyberpi.console.println("Press “B” to start obstacle avoidance")
    cyberpi.console.println("Press “A” to restart")
    while not cyberpi.controller.is_press('b'):
      # DO SOMETHING
      pass
    while True:
      #
      text_for_console = 'dist=' + str(mbuild.ultrasonic2.get(1)) + ' pitch=' + str(cyberpi.get_pitch()) + ' accel=' + str(cyberpi.get_acc('x'))
      text_line0 = 'dist=' + str(mbuild.ultrasonic2.get(1))
      text_line1 = 'y=' + str(cyberpi.get_yaw()) + ' p=' + str(cyberpi.get_pitch()) + ' r=' + str(cyberpi.get_roll())
      text_line2 = 'accX=' + str(cyberpi.get_acc('x')) + ' accY=' + str(cyberpi.get_acc('y')) + ' accZ=' + str(cyberpi.get_acc('z'))
      #cyberpi.console.println(cyberpi.get_acc('x'))
      cyberpi.console.println(text_line0)
      cyberpi.console.println(text_line1)
      cyberpi.console.println(text_line2)
    
    
      if mbuild.ultrasonic2.get(1) > 20:
        mbot2.forward(100)
      else:
        if random.randint(1, 2) == 1:
          mbot2.turn_left(50)
          time.sleep(1)
        else:
          mbot2.turn_right(50)
          time.sleep(1)

@event.is_press('a')
def is_btn_press():
    cyberpi.restart()
